import { categories } from './categories'
import { countries } from './countries'

export const places = [
  {
    name: 'Come Back Alive',
    link: 'https://www.comebackalive.in.ua/',
    categories: [categories.army],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Ukraine Now',
    link: 'https://ukraine.ua/news/donate-to-the-nbu-fund/',
    categories: [categories.army],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'ArmySOS',
    link: 'https://armysos.com.ua/en/',
    categories: [categories.army],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Razom',
    link: 'https://razomforukraine.org/donate/',
    categories: [categories['medical-supplies']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'United Help Ukraine',
    link: 'https://www.facebook.com/donate/337101825010055/',
    categories: [categories['medical-supplies']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Sunflower of Peace',
    link: 'https://www.facebook.com/donate/507886070680475/',
    categories: [categories['medical-supplies']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'VostokSOS',
    link: 'https://vostok-sos.org/en/make-a-donation/',
    categories: [categories['humanitarian-aid']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Revived Soldiers',
    link: 'https://www.rsukraine.org/',
    categories: [categories.army],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Hospitallers',
    link: 'https://www.facebook.com/hospitallers/posts/2953630548255167',
    categories: [categories['medical-supplies']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Ukranian Red Cross',
    link:
      'https://redcross.org.ua/en/2022/02/donate-to-support-the-ukrainian-red-cross-to-help-civilians-in-this-difficult-time-for-ukraine/',
    categories: [categories['volunteer-help']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Finish Red Cross',
    link: 'https://www.redcross.fi/donate/',
    categories: [categories['volunteer-help']],
    countries: [countries.FI],
    description: '',
  },
  {
    name: 'German Red Cross',
    link: 'https://www.drk.de/en/donate/donate-online/',
    categories: [categories['volunteer-help']],
    countries: [countries.DE],
    description: '',
  },
  {
    name: 'Lunacy Berlin',
    link: 'https://www.facebook.com/Lunacyberlin/',
    categories: [categories['volunteer-help'], categories['humanitarian-aid']],
    countries: [countries.DE],
    description: '',
  },
  {
    name: 'British Red Cross',
    link: 'https://donate.redcross.org.uk/appeal/ukraine-crisis-appeal',
    categories: [categories['humanitarian-aid']],
    countries: [countries.GB],
    description: '',
  },
  {
    name: 'Ukranian Women Veteran Movement',
    link: 'https://www.uwvm.org.ua/?page_id=3031&lang=en',
    categories: [categories['veteran-help']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Voices of Children',
    link: 'https://voices.org.ua/en/',
    categories: [categories.children],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Insight',
    link: 'https://www.insight-ukraine.org/en/join-donate/',
    categories: [categories['vulnerable-groups']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Help Roma Families',
    link:
      'https://www.crowdfunder.co.uk/p/fundraising-for-roma-families-in-ukrainian-crisis',
    categories: [categories['vulnerable-groups']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Help Ukrainian media keep going!',
    link: 'https://www.gofundme.com/f/keep-ukraines-media-going',
    categories: [categories.journalism],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'The Kyiv Independent',
    link: 'https://kyivindependent.com/',
    categories: [categories.journalism],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Nova Ukraine',
    link: 'https://www.facebook.com/donate/1137971146948461/10161497920013976/',
    categories: [categories['humanitarian-aid']],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'Unicef',
    link:
      'https://www.unicefusa.org/stories/amid-stress-and-sorrow-support-families-fleeing-ukraine/39558?form=FUNGNXBYXDH&utm_campaign=20220223_Emergencies&utm_medium=Organic&utm_source=HelpUkraineFeb2022&utm_content=TakeActionDonateUkraineFeb2022&ms=Organic_PRL_2022_Emergencies_20220223_HelpUkraineFeb2022_TakeActionDonateUkraineFeb2022_none_none&initialms=Organic_PRL_2022_Emergencies_20220223_HelpUkraineFeb2022_TakeActionDonateUkraineFeb2022_none_none',
    categories: [categories.children, categories['humanitarian-aid']],
    countries: [countries.US],
    description: '',
  },
  {
    name: 'Territory of Good Deeds',
    link: 'https://vuf-td.space/en/',
    categories: [
      categories.children,
      [categories['humanitarian-aid']],
      categories.army,
    ],
    countries: [countries.UA],
    description: '',
  },
  {
    name: 'People In Need',
    link: 'https://www.peopleinneed.net/',
    categories: [categories['humanitarian-aid']],
    countries: [countries.CZ],
    description: '',
  },
  {
    name: 'CARE',
    link:
      'https://my.care.org/site/Donation2?df_id=31067&mfc_pref=T&31067.donation=form1&s_src=172223UCF000',
    categories: [categories['humanitarian-aid']],
    countries: [countries.US, countries.DE],
    description: '',
  },
  {
    name: 'Save the children',
    link: 'https://www.savethechildren.org/',
    categories: [categories.children],
    countries: [countries.US],
    description: '',
  },
  {
    name: 'Mercy Corps',
    link: 'https://www.mercycorps.org/',
    categories: [categories['humanitarian-aid']],
    countries: [countries.US],
    description: '',
  },
  {
    name: 'Medical Corps',
    link:
      'https://give.internationalmedicalcorps.org/page/99837/donate/1?ea.tracking.id=DP~UA22~DPLBU2202',
    categories: [
      [categories['medical-supplies']],
      categories['humanitarian-aid'],
    ],
    countries: [countries.US],
    description: '',
  },
  {
    name: 'Polish Humanitarian Action',
    link: 'https://www.pah.org.pl/en/',
    categories: [categories['humanitarian-aid']],
    countries: [countries.PL],
    description: '',
  },
  {
    name: 'The Association for Legal Intervention',
    link: 'https://interwencjaprawna.pl/en/get-involved/donate/',
    categories: [categories['humanitarian-aid']],
    countries: [countries.PL],
    description: '',
  },
  {
    name: 'PCPM',
    link: 'https://pcpm.org.pl/ukraina',
    categories: [categories['humanitarian-aid']],
    countries: [countries.PL],
    description: '',
  },
  {
    name: 'HIAS',
    link: 'https://www.hias.org/',
    categories: [categories['humanitarian-aid']],
    countries: [countries.PL, countries.US],
    description: '',
  },
]
